### ISSUE TITLE
Todo: Add names

### ISSUE THREAD

**Issue by ivandrofly** [SubtitleEdit/subtitleedit#131]
- [x] pt_PT_names_etc
- [x] fr_Fra_names_etc
- [x] en_GB_names_etc
